### ISSUE TITLE
500 error when logging out of the API console

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#247]
I got a 500 error after logging out of the API console on Heroku. Link:

https://lore-ci.herokuapp.com/api/v1/api-auth/logout/?next=/api/v1/repositories/george-test/vocabularies/

**Comment by carsongee** [comment]
```
015-06-26T22:09:50.007698+00:00 app[web.1]: [2015-06-26 22:09:48] ERROR 9 [django.request] base.py:256 - [6c505d00-0862-41b9-bc23-66f25326982e] - Internal Server Error: /api/v1/api-auth/logout/
2015-06-26T22:09:50.007704+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T22:09:50.007707+00:00 app[web.1]:     response = middleware_method(request, callback, callback_args, callback_kwargs)
2015-06-26T22:09:50.007706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 125, in get_response
2015-06-26T22:09:50.007709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_cas_ng/middleware.py", line 40, in process_view
2015-06-26T22:09:50.007710+00:00 app[web.1]:     return cas_logout(request, *view_args, **view_kwargs)
2015-06-26T22:09:50.007712+00:00 app[web.1]: TypeError: logout() got an unexpected keyword argument 'template_name'
2015-06-26T22:09:50.008060+00:00 app[web.1]: ERROR:django.request:Internal Server Error: /api/v1/api-auth/logout/
2015-06-26T22:09:50.008066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django_cas_ng/middleware.py", line 40, in process_view
2015-06-26T22:09:50.008062+00:00 app[web.1]: Traceback (most recent call last):
2015-06-26T22:09:50.008064+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 125, in get_response
2015-06-26T22:09:50.008065+00:00 app[web.1]:     response = middleware_method(request, callback, callback_args, callback_kwargs)
2015-06-26T22:09:50.008067+00:00 app[web.1]:     return cas_logout(request, *view_args, **view_kwargs)
2015-06-26T22:09:50.008068+00:00 app[web.1]: TypeError: logout() got an unexpected keyword argument 'template_name'
```
