### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#517]
I'm not sure the cause, but usually these are caused by bad form validation or race conditions...

```
Internal Server Error: /api/v1/repositories/ferdit/learning_resources/20435/
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/generics.py", line 260, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/mixins.py", line 77, in partial_update
    return self.update(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/mixins.py", line 69, in update
    self.perform_update(serializer)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/mixins.py", line 73, in perform_update
    serializer.save()
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/serializers.py", line 164, in save
    self.instance = self.update(self.instance, validated_data)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/serializers.py", line 811, in update
    setattr(instance, attr, value)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1211, in __set__
    manager.add(*value)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/related.py", line 984, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1108, in _add_items
    for obj_id in new_ids
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 392, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 937, in _batched_insert
    using=self.db)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "taxonomy_term_learning_resource_term_id_learningresource_id_key"
DETAIL:  Key (term_id, learningresource_id)=(337, 20435) already exists.

```

**Comment by ShawnMilo** [comment]
It's a shame the traceback doesn't contain a single line of code we wrote. That makes it harder to find, duplicate, and fix. :cry:

**Comment by carsongee** [comment]
It at least gives the URL, I'm guessing something client side like the javascript is likely the issue, and the backend is responding appropriately

**Comment by ShawnMilo** [comment]
Yeah, the URL helps. This ties into the learning I'm doing about Django REST Framework, so maybe I'll have some insight into it before George gets back from vacation. Amir is also looking into the framework for a ticket he's working on. Education is good.

**Comment by pdpinch** [comment]
I was trying to edit the description on a resource. It's possible I hit save too many times, but things were really sloooow.

---

I am mobile.

**Comment by noisecapella** [comment]
Maybe related to this? https://code.djangoproject.com/ticket/19544

**Comment by carsongee** [comment]
I just saw this again on lore-ci: Internal Server Error: /api/v1/repositories/animating-stuffed-animals/learning_resources/6366/  if that was maybe someone investigating this
