### ISSUE TITLE
Vocabulary with name 'run', 'resource_type', 'course' will crash server

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#774]
After adding a 'run' vocabulary I get this everytime I try to load my repository on lore-ci:

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/component_djangorestframework.py", line 27, in _nr_wrapper_APIView_dispatch_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/statsd/client.py", line 30, in _wrapped
    return_value = f(*args, **kwargs)
  File "./rest/views.py", line 948, in list
    page = self.paginate_queryset(queryset)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/generics.py", line 172, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/pagination.py", line 261, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
  File "./search/utils.py", line 401, in __getitem__
    setattr(hit, field_name, getattr(hit, field_name)[0])
  File "/app/.heroku/python/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 105, in __getattr__
    '%r object has no attribute %r' % (self.__class__.__name__, attr_name))
AttributeError: 'Result' object has no attribute 'run'
```

**Comment by noisecapella** [comment]
This happens because we use the vocabulary name as a key in the elasticsearch mapping which also has `run`, `resource_type`, `text`, all the fields we use. ~~I think we ought to use a single mapping name like `terms` as the key mapping and have all vocabularies and terms under it.~~ It seems like that would interfere with the missing aggregation, using a `vocab_` prefix may work to prevent collision instead.

**Comment by noisecapella** [comment]
We should also make sure we switch to using vocabulary and term slugs instead of names like we use currently.

**Comment by pdpinch** [comment]
George, is this issue limited to you the repository with the errant vocabulary, or will it affect the entire app?

Because that's what I'm seeing now, on lore-ci...

Will refreshing the index after this is merged fix the index?

**Comment by noisecapella** [comment]
It should be limited to the repository with the problem since the search is limited to one repository. I'll investigate to make sure that's the case

**Comment by noisecapella** [comment]
After looking at it I think that since the mapping is shared with all repositories, the run field is different for all searches which causes this exception. The PR fixed the problem on my local machine after reindexing
